### ISSUE TITLE
Inference on CPU

### ISSUE THREAD

**Issue by abhigoku10** [brian-h-wang/LDLS#1]
@brian-h-wang hi thanks for sharing this wonderful code , i have few queries 
1. can we perform the inference on CPU , is there CPU code available 
2.any instance segmenation or sematic segmentation model output can be used ?
3.what is the performance and accuracy of the of the work 

Thanks in advance

**Comment by brian-h-wang** [comment]
Just saw this now - sorry for the late reply:
1. The current version of the algorithm is GPU-only, but the "version1" branch has an older version which has slightly worse performance but can run on CPU.
2. Yes, Mask-RCNN can be switched out for any instance/semantic segmentation model.
3. Please see the paper linked from the readme for this info
