### ISSUE TITLE
Workflow Queries

### ISSUE THREAD

**Issue by abhigoku10** [brian-h-wang/LDLS#2]
@brian-h-wang thanks for open sourcing your work which is saver for me currently !! i have few queries 
Q1. Is semi supervised graph based method dependent on the density of points in the point cloud 
Q2. Which part of the code performs graph creation and label diffusion can you please point it out 
Q3.Can we use LDLS for static objects like trees , buildings ,poles and lanes 
Q4 what is inference time for the whole code follow 
Q5.Which part of the code performs the proper segmentation by outlier removal 
Q6. Compared to Kitti dataset point density my custom dataset has less points so can i use LDLS

Thanks for the response

**Comment by brian-h-wang** [comment]
Thanks for the questions!
1) The algorithm will tend to work better if the point cloud is denser. However, it doesn't explicitly use point density in any way (as compared to  DBSCAN clustered for example)
2) Please see the LidarSegmentation.create_graph() and LidarSegmentation.run() methods in segmentation.py
3) Yes, the only requirement is having an image segmentation model which is trained to detect those object classes.
4) Please see the paper for a discussion of runtime - in our experiments the code ran at about 3 FPS.
5) See segmentation.py lines 569-577
6) It'd be worth trying out, but the more points you have, the better LDLS will work. KITTI uses a 64-scan Velodyne lidar. We've tried LDLS with a 16-scan Velodyne and got decent results for nearby objects, but performance definitely falls off for further away objects where the points are very sparse with the 16-scan lidar.

Hope this helps!
